### ISSUE TITLE
Bug with Sass version of str-index function

### ISSUE THREAD

**Issue by ggilder** [square/apropos#4]
`str-index` now returns null instead of -1 when the substring is not found; this breaks apropos mixins. test case at https://github.com/square/apropos/tree/sass-str-index-bug

**Comment by ghepting** [comment]
Wasn't this resolved in f1686c30e62053b5f2f01d8b3e65376bf564beca?

**Comment by ghepting** [comment]
@ggilder that branch doesn't appear to exist anymore, what is the status of this?

**Comment by ghepting** [comment]
This was resolved in: https://github.com/square/apropos/commit/f1686c30e62053b5f2f01d8b3e65376bf564beca
